[package]
name = "rendezvous"
version = "0.1.0"
description = "Easier rendezvous channels for thread synchronization"
authors = ["Markus Mayer <github@widemeadows.de>"]
homepage = "https://github.com/sunsided/rendezvous-rs"
repository = "https://github.com/sunsided/rendezvous-rs"
categories = ["asynchronous"]
license = "EUPL-1.2"
readme = "README.md"
edition = "2021"
